package io.imking.core.domain;

import java.io.Serializable;
import java.util.Date;

public class KDCrowdTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.operatorId
     *
     * @mbg.generated
     */
    private Integer operatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.reward
     *
     * @mbg.generated
     */
    private Long reward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.taskType
     *
     * @mbg.generated
     */
    private Byte tasktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.tagType
     *
     * @mbg.generated
     */
    private Integer tagtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_crowd_task.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.id
     *
     * @return the value of kd_crowd_task.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.id
     *
     * @param id the value for kd_crowd_task.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.userId
     *
     * @return the value of kd_crowd_task.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.userId
     *
     * @param userid the value for kd_crowd_task.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.operatorId
     *
     * @return the value of kd_crowd_task.operatorId
     *
     * @mbg.generated
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.operatorId
     *
     * @param operatorid the value for kd_crowd_task.operatorId
     *
     * @mbg.generated
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.title
     *
     * @return the value of kd_crowd_task.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.title
     *
     * @param title the value for kd_crowd_task.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.reward
     *
     * @return the value of kd_crowd_task.reward
     *
     * @mbg.generated
     */
    public Long getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.reward
     *
     * @param reward the value for kd_crowd_task.reward
     *
     * @mbg.generated
     */
    public void setReward(Long reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.taskType
     *
     * @return the value of kd_crowd_task.taskType
     *
     * @mbg.generated
     */
    public Byte getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.taskType
     *
     * @param tasktype the value for kd_crowd_task.taskType
     *
     * @mbg.generated
     */
    public void setTasktype(Byte tasktype) {
        this.tasktype = tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.tagType
     *
     * @return the value of kd_crowd_task.tagType
     *
     * @mbg.generated
     */
    public Integer getTagtype() {
        return tagtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.tagType
     *
     * @param tagtype the value for kd_crowd_task.tagType
     *
     * @mbg.generated
     */
    public void setTagtype(Integer tagtype) {
        this.tagtype = tagtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.avatar
     *
     * @return the value of kd_crowd_task.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.avatar
     *
     * @param avatar the value for kd_crowd_task.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.content
     *
     * @return the value of kd_crowd_task.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.content
     *
     * @param content the value for kd_crowd_task.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.createTime
     *
     * @return the value of kd_crowd_task.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.createTime
     *
     * @param createtime the value for kd_crowd_task.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.status
     *
     * @return the value of kd_crowd_task.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.status
     *
     * @param status the value for kd_crowd_task.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_crowd_task.explain
     *
     * @return the value of kd_crowd_task.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_crowd_task.explain
     *
     * @param explain the value for kd_crowd_task.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain;
    }
}