package io.imking.core.domain;

import java.io.Serializable;
import java.util.Date;

public class KDMedals implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_medals.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_medals.medalCode
     *
     * @mbg.generated
     */
    private String medalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_medals.medalName
     *
     * @mbg.generated
     */
    private String medalname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_medals.imgsrc
     *
     * @mbg.generated
     */
    private String imgsrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_medals.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_medals.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_medals.id
     *
     * @return the value of kd_medals.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_medals.id
     *
     * @param id the value for kd_medals.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_medals.medalCode
     *
     * @return the value of kd_medals.medalCode
     *
     * @mbg.generated
     */
    public String getMedalcode() {
        return medalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_medals.medalCode
     *
     * @param medalcode the value for kd_medals.medalCode
     *
     * @mbg.generated
     */
    public void setMedalcode(String medalcode) {
        this.medalcode = medalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_medals.medalName
     *
     * @return the value of kd_medals.medalName
     *
     * @mbg.generated
     */
    public String getMedalname() {
        return medalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_medals.medalName
     *
     * @param medalname the value for kd_medals.medalName
     *
     * @mbg.generated
     */
    public void setMedalname(String medalname) {
        this.medalname = medalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_medals.imgsrc
     *
     * @return the value of kd_medals.imgsrc
     *
     * @mbg.generated
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_medals.imgsrc
     *
     * @param imgsrc the value for kd_medals.imgsrc
     *
     * @mbg.generated
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_medals.remark
     *
     * @return the value of kd_medals.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_medals.remark
     *
     * @param remark the value for kd_medals.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_medals.createTime
     *
     * @return the value of kd_medals.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_medals.createTime
     *
     * @param createtime the value for kd_medals.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}