package io.imking.core.domain;

import java.io.Serializable;
import java.util.Date;

public class KDUserMedal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user_medal.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user_medal.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user_medal.medalId
     *
     * @mbg.generated
     */
    private Long medalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user_medal.bindUserid
     *
     * @mbg.generated
     */
    private Long binduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user_medal.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user_medal.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user_medal.id
     *
     * @return the value of kd_user_medal.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user_medal.id
     *
     * @param id the value for kd_user_medal.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user_medal.userid
     *
     * @return the value of kd_user_medal.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user_medal.userid
     *
     * @param userid the value for kd_user_medal.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user_medal.medalId
     *
     * @return the value of kd_user_medal.medalId
     *
     * @mbg.generated
     */
    public Long getMedalid() {
        return medalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user_medal.medalId
     *
     * @param medalid the value for kd_user_medal.medalId
     *
     * @mbg.generated
     */
    public void setMedalid(Long medalid) {
        this.medalid = medalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user_medal.bindUserid
     *
     * @return the value of kd_user_medal.bindUserid
     *
     * @mbg.generated
     */
    public Long getBinduserid() {
        return binduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user_medal.bindUserid
     *
     * @param binduserid the value for kd_user_medal.bindUserid
     *
     * @mbg.generated
     */
    public void setBinduserid(Long binduserid) {
        this.binduserid = binduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user_medal.remark
     *
     * @return the value of kd_user_medal.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user_medal.remark
     *
     * @param remark the value for kd_user_medal.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user_medal.createTime
     *
     * @return the value of kd_user_medal.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user_medal.createTime
     *
     * @param createtime the value for kd_user_medal.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}