package io.imking.core.domain;

import java.io.Serializable;
import java.util.Date;

public class KDUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.slat
     *
     * @mbg.generated
     */
    private String slat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.sex
     *
     * @mbg.generated
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.brithday
     *
     * @mbg.generated
     */
    private String brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.trueName
     *
     * @mbg.generated
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.workyears
     *
     * @mbg.generated
     */
    private Integer workyears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.dream
     *
     * @mbg.generated
     */
    private String dream;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.introduce
     *
     * @mbg.generated
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.balance
     *
     * @mbg.generated
     */
    private Long balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.points
     *
     * @mbg.generated
     */
    private Long points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.id
     *
     * @return the value of kd_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.id
     *
     * @param id the value for kd_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.userName
     *
     * @return the value of kd_user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.userName
     *
     * @param username the value for kd_user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.pwd
     *
     * @return the value of kd_user.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.pwd
     *
     * @param pwd the value for kd_user.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.email
     *
     * @return the value of kd_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.email
     *
     * @param email the value for kd_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.slat
     *
     * @return the value of kd_user.slat
     *
     * @mbg.generated
     */
    public String getSlat() {
        return slat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.slat
     *
     * @param slat the value for kd_user.slat
     *
     * @mbg.generated
     */
    public void setSlat(String slat) {
        this.slat = slat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.avatar
     *
     * @return the value of kd_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.avatar
     *
     * @param avatar the value for kd_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.sex
     *
     * @return the value of kd_user.sex
     *
     * @mbg.generated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.sex
     *
     * @param sex the value for kd_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.phone
     *
     * @return the value of kd_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.phone
     *
     * @param phone the value for kd_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.brithday
     *
     * @return the value of kd_user.brithday
     *
     * @mbg.generated
     */
    public String getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.brithday
     *
     * @param brithday the value for kd_user.brithday
     *
     * @mbg.generated
     */
    public void setBrithday(String brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.nickName
     *
     * @return the value of kd_user.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.nickName
     *
     * @param nickname the value for kd_user.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.trueName
     *
     * @return the value of kd_user.trueName
     *
     * @mbg.generated
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.trueName
     *
     * @param truename the value for kd_user.trueName
     *
     * @mbg.generated
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.status
     *
     * @return the value of kd_user.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.status
     *
     * @param status the value for kd_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.createTime
     *
     * @return the value of kd_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.createTime
     *
     * @param createtime the value for kd_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.updateTime
     *
     * @return the value of kd_user.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.updateTime
     *
     * @param updatetime the value for kd_user.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.address
     *
     * @return the value of kd_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.address
     *
     * @param address the value for kd_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.workyears
     *
     * @return the value of kd_user.workyears
     *
     * @mbg.generated
     */
    public Integer getWorkyears() {
        return workyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.workyears
     *
     * @param workyears the value for kd_user.workyears
     *
     * @mbg.generated
     */
    public void setWorkyears(Integer workyears) {
        this.workyears = workyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.job
     *
     * @return the value of kd_user.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.job
     *
     * @param job the value for kd_user.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.dream
     *
     * @return the value of kd_user.dream
     *
     * @mbg.generated
     */
    public String getDream() {
        return dream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.dream
     *
     * @param dream the value for kd_user.dream
     *
     * @mbg.generated
     */
    public void setDream(String dream) {
        this.dream = dream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.introduce
     *
     * @return the value of kd_user.introduce
     *
     * @mbg.generated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.introduce
     *
     * @param introduce the value for kd_user.introduce
     *
     * @mbg.generated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.balance
     *
     * @return the value of kd_user.balance
     *
     * @mbg.generated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.balance
     *
     * @param balance the value for kd_user.balance
     *
     * @mbg.generated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.points
     *
     * @return the value of kd_user.points
     *
     * @mbg.generated
     */
    public Long getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.points
     *
     * @param points the value for kd_user.points
     *
     * @mbg.generated
     */
    public void setPoints(Long points) {
        this.points = points;
    }
}